### PR TITLE
Fixed naive balance comparison

### PR DESCRIPTION
**Pull request by Jacotsu**
Fixed naive balance comparison that would make ending balance check fail often due to rounding error

### CODE REVIEW

**Comment by kedder** [comment]
Thanks! The real problem is that these are `float`s instead of `Decimal`s, of course.

**Comment by kedder** [comment]
@Jacotsu, do you want a release?

**Comment by Jacotsu** [comment]
> @Jacotsu, do you want a release?

what do you mean? At the moment i'm using my fork so i don't have any urgencies, so feel free to follow your normal release cycle

**Comment by kedder** [comment]
sounds good!

**Pull request merged**
