### PR TITLE
Fix STOCKINFO tag generation for investment files

### PR DESCRIPTION
**Pull request by jaik03**
OFX STOCKINFO tags need to be closed and repeated for each individual security. Leaving the tag off leads to unexpected behavior in GNUCash (and potentially other software).

### CODE REVIEW

**Comment by kedder** [comment]
Yeah, according to [this] you seem to be right.

image

Meanwhile, it looks like ofxstatement build got completely broken. I'll fix it in a separate PR.

**Comment by jaik03** [comment]
Thanks. I'm developing a plugin to import JSON brokerage exports from Schwab, and this was giving me fits testing the import into GNUCash. I'll have another couple minor PRs as I go.

**Comment by kedder** [comment]
Could you please rebase this branch on master (to fix the build)?

**Comment by jaik03** [comment]
> Could you please rebase this branch on master (to fix the build)?

Done!

**Review by kedder — APPROVED** [review]
LGTM

**Pull request merged**
