### PR TITLE
Remove pkg resources

### PR DESCRIPTION
**Pull request by jaik03**
Updated plugins.py and tool.py to pkg_resources to use importlib.metadata instead. Fixed tests to reflect using entry_points call to populate list_plugins and get_plugins.

For reference on pkg_resources:
[https://setuptools.pypa.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources](url)

### CODE REVIEW

**Comment by jaik03** [comment]
I neglected to run the "mypy src" check. I'm able to fix it but now I have to rectify it in the test_plugins as well.

**Comment by kedder** [comment]
Hopefully we are not breaking existing plugins.

**Comment by jaik03** [comment]
I'm going to close this until I can get the build to work correctly. I have to install importmetadata-lib on python versions less than 3.10 and I can't seem to get the pip lockfile to work correctly.

**Comment by jaik03** [comment]
I tested this workflow on my GitHub and it was successfully building. Ready for review now.

Considering the nature of the changes, it shouldn't break other plugins as their interfacing through console scripts entry points. I've tested by loading several different plugins as well as the one I'm developing and it remains functional, though I don't have much ability to call the other plugins as I don't have test data. I could see it break a plugin if they were importing pkg_resources for use in their code without declaring as a dependency, but that's an easy fix. They should also probably update to move away from pkg_resources in any case.

You can also sit on this PR, the negative performance factors of pkg_resources probably aren't super impactful for most people's use case, but the library is deprecated so at some point it will have to be done. I mostly did this to explore the recent python packaging trends and get a feel for some of the development factors. If there are other ways you want to test or explore this before accepting the PR, let me know.

**Review by kedder — APPROVED** [review]

**Comment by kedder** [comment]
Thank you so much for this! This switch have been long overdue.

**Comment by jaik03** [comment]
NP. Thanks for creating and maintaining this. It's very helpful now that my bank eliminated direct connect OFX, and I'm enjoying exploring about the OFX standard and Python.

**Comment by kedder** [comment]
Let me know when you want to cut a new version.

**Comment by jaik03** [comment]
I've got a few more changes to make. I'm working on one within ofx.py to enhance the security name information it returns when it's available as part of the statement that I'd prefer to work out first.

**Comment by kedder** [comment]
sound good!

**Pull request merged**
